### ISSUE TITLE
Consider better project / website name

### ISSUE THREAD

**Issue by jonyo** [geodesicsolutions-community/website#2]
The `Geodesic Solutions Community` is quite a mouth full.  If you think of any good names, reply here!  I'm open to even changing the org name in github if we think of a better one (especially if it is shorter).

Maybe `GeoCore Phoenix Project`?  ¯\\\_(ツ)\_/¯

**Comment by jonyo** [comment]
We could even use a different domain name if appropriate, and just have the current one set up to redirect to the new one.

**Comment by hektyc** [comment]
Jonyo, how about GeoCoreCE short for "GeoCore Community Edition"?

**Comment by jonyo** [comment]
Closing this out, we pretty much decided on @imxweb 's suggestion of GeoCore CE.  Some places we spell it out `Community Edition` but any place we need brevity we use CE.
