### ISSUE TITLE
Revive the old bug for independent upgrades

### ISSUE THREAD

**Issue by ghost** [geodesicsolutions-community/website#4]
Hey Jonyo,

One of the long time complaints of my customers, and the site owners on Geo was that the upgrades could not be purchased independently of the ad placement periods. This was a huge issue with many, and one thing many other scripts had, which lacked in geo.

I wish I had the knowledge to code and help on these issues, but you do want something that works... right? lol.

Dale

**Comment by jonyo** [comment]
@NobleGroupUSA Sorry for the late reply, I meant to reply and uh, basically forgot...  Sorry bout that!  (hey I try to be honest 😉 )

This would be a great feature!  I kind of thought they had added it after I left but I did not dig that deep yet to look.

For those reading this, what he's talking about, is being able to add, say "bold upgrade" or a "featured listing" paid "upgrade" for a listing.  But not do it as "part of" renewing the listing itself, the upgrade could be done at any time.

It would be a big one though (again, assuming it is not already in there somewhere, I have not looked yet), I don't think it would happen without someone hiring a developer to do it.  Or if there are any developers + site owner in one that happened to want this feature bad enough, they could make it for themselves and put in a PR to add it to the base code.

**Comment by jonyo** [comment]
Oh, side note for future:  This is the `website` project, for software features and bugs, check out the `geodesic-community` project issues [here](https://github.com/geodesicsolutions-community/geocore-community/issues)
